### ISSUE TITLE
Criar um gitbook para o projeto

### ISSUE THREAD

**Issue by teles** [woliveiras/vim-para-noobs#1]
É possível criar um gitbook para o projeto e disponibilizá-lo via gh-pages, para isso:

* Importar o gitbook em gh-pages;
* Configurar o gitbook como desejar no arquivo book.json;
* Inserir as seções do gitbook no arquivo summary.md;
* Buildar o gitbook e pushá-lo para gh-pages

**Comment by woliveiras** [comment]
Shoow! Farei! :smile:

**Comment by woliveiras** [comment]
Tá lá @teles!

[Vim para Noobs](http://woliveiras.com.br/vim-para-noobs/livro/) ;D

**Comment by teles** [comment]
Sucesso, @woliveiras !!

**Comment by adeonir** [comment]
404 no Gitbook =(

**Comment by teles** [comment]
@adeonir, aqui está funcionando na url https://woliveiras.com.br/vimparanoobs

**Comment by adeonir** [comment]
@teles, realmente esse link está funcionando, mas no final do readme não.

**Comment by teles** [comment]
Verdade, @adeonir . Fiz um PR propondo a correção disso :)

**Comment by woliveiras** [comment]
Valeu @adeonir
